### ISSUE TITLE
Flash插件初始化失败，请更新您的FlashPlayer版本之后重试！

### ISSUE THREAD

**Issue by wang517127** [jasl/ueditor_rails#11]
图片上传提示Flash插件初始化失败，请更新您的FlashPlayer版本之后重试！

**Comment by wang517127** [comment]
@jasl

**Comment by jasl** [comment]
你的 flash 版本是多少 有没有启用 Chrome 新版（其他浏览器我没注意）已经默认禁用 Flash 插件了，你要查阅一下资料怎么开启

**Comment by wang517127** [comment]
@jasl 灰常感谢，Chrome 添加后可以了， 但是我疑问的是，我的Chrome的设置是先询问，怎么没有询问？

**Comment by jasl** [comment]
这个是 Chrome 的产品设计了，目前各大浏览器都处于强制退役 Flash 的阶段，对 Flash 的限制只会越来越多

**Comment by wang517127** [comment]
感谢指导，现在有个新问题能否解答下，关于图片上传，我配置了显示多图上传，但是工具栏还是只有单图上传，没有多图上传按钮，此外，我看官网的demo还有配置config.json的 rails这边怎么配置呢？ 再次感谢大神赐教 @jasl

**Comment by jasl** [comment]
年代久远，具体怎么搞的忘了，不过可以试试 复制 https://github.com/jasl/ueditor_rails/blob/master/app/assets/javascripts/ueditor_rails/_config.js.erb

到你项目app/assets/javascripts/ueditor_rails/ 下（没有就建立），然后编辑你复制的 _config.js.erb

原理是这样，Assets Pipeline 在 //= require 的时候，会先看项目的 assets 里有没有同名文件，如果有，就直接用，否则才去看其他的 path 以及 gem 的
